openapi: 3.1.0
info:
  contact:
    email: info@mod.construction
    name: Contact us
    url: https://mod.construction
  description: "mod-dlm is an open source domain specific language to describe prefab\
    \ construction elements. This project provides tools for defining entity models\
    \ and automatically generating CRUD APIs, enabling suppliers to create and manage\
    \ catalogs of their products easily."
  license:
    name: MIT
    url: https://github.com/mod-construction/mod-dlm/blob/main/LICENSE
  title: mod-dlm API
  version: 1.0.7
  x-logo:
    url: mod-dlm-logo.png
    backgroundColor: '#FFFFFF'
    altText: mod-dlm logo
servers:
- description: The dev server.
  url: http://localhost:8080
- description: The production server.
  url: https://mod.construction
security:
- apiKey: []
  bearer: []
paths:
  /element:
    get:
      description: Gets an element from the database.
      operationId: getElement
      parameters:
      - description: A unique identifier for an element
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/ElementId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrefabElement'
          description: The element was retrieved successfully.
        "400":
          description: Bad request.
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: An element with the specified ID was not found.
      summary: Get an element
      x-accepts:
      - application/json
    post:
      description: Creates a new element in the database.
      operationId: createElement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElementCreate'
        description: The element to create.
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrefabElement'
          description: The element was created successfully.
        "400":
          description: Bad request.
        "401":
          description: Authorization information is missing or invalid.
      summary: Create a new element
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    ElementId:
      description: A unique identifier for an element
      example: 4dd643ff-7ec7-4666-9c88-50b7d3da34e4
      format: uuid
      type: string
    PrefabElement:
      description: Prefab Element
      example:
        boundingBox:
          depth: 1.4658129805029452
          width: 0.8008281904610115
          height: 6.027456183070403
        images:
        - images
        - images
        installationAndConnectivity:
          installationTime: installationTime
          connectionType: Bolt-on
          compatibility: Steel Frame
        buildingSystem: Wall
        dimensional:
          width:
            min: 5.962133916683182
            max: 5.637376656633329
          length:
            min: 5.962133916683182
            max: 5.637376656633329
          height:
            min: 5.962133916683182
            max: 5.637376656633329
        structuralProperties:
          windLoadResistance: Class A
          loadBearingCapacity:
            unit: "N"
            loadDistribution: loadDistribution
            maximumLoad: 2.3021358869347655
          seismicResistance: Zone 1
        lifecycleAndMaintenance:
          maintenanceRequirements: maintenanceRequirements
          warranty: warranty
          expectedLifespan: expectedLifespan
        description: description
        documentationAndCompliance:
          technicalSpecifications: technicalSpecifications
          certifications:
            certificationTypes:
            - certificationTypes
            - certificationTypes
            regulatoryApprovals:
            - regulatoryApprovals
            - regulatoryApprovals
        sustainability:
          countryOfManufacturing: countryOfManufacturing
          recyclability: 0%
          classification: A+
          energyEfficiency: R-1
          VOCEmissions: None
        productCategory: Boarding
        aestheticAndCustomizationOptions:
          colorOptions:
          - colorOptions
          - colorOptions
          texture: texture
          modularAdaptability: modularAdaptability
        performance:
          thermalTransmittance: 1.4122802483006218
          acousticProperties:
            acousticPerformance: acousticPerformance
            soundInsulationRating: soundInsulationRating
          resistanceToFireClassification: A1
        material:
          finishMaterial: Timber
          structuralMaterial: Timber
        name: name
        id: 4dd643ff-7ec7-4666-9c88-50b7d3da34e4
        economicFactors:
          manufacturingLeadTime: manufacturingLeadTime
          costPerUnit: 9.301444243932576
      properties:
        id:
          description: A unique identifier for an element
          example: 4dd643ff-7ec7-4666-9c88-50b7d3da34e4
          format: uuid
          type: string
        name:
          type: string
        description:
          type: string
        boundingBox:
          $ref: '#/components/schemas/PrefabElement_boundingBox'
        images:
          items:
            type: string
          type: array
        buildingSystem:
          enum:
          - Wall
          - Balcony
          - Pod
          - Frame
          - Facade
          - Floors
          - Modules
          - Plants
          - Roofs
          - Stairs
          type: string
        productCategory:
          enum:
          - Boarding
          - Solid Wall Panels
          - Closed Wall Panels
          - Twinwall
          - Open Wall Panels
          - Structural Insulated Panels (SIPs)
          - Insulated Concrete Panels
          - Prefabricated Balcony
          - Pod
          - Whole Building System
          - Structural Frame
          - Facade System
          - Hollowcore Floor
          - Concrete Lattice Floor
          - Floor Cassettes
          - Solid Floor Panels
          - Volumetric module
          - Prefabricated Plant
          - Roof Panel
          - Roof Truss
          - Prefabricated Stairs
          type: string
        material:
          $ref: '#/components/schemas/PrefabElement_material'
        dimensional:
          $ref: '#/components/schemas/PrefabElement_dimensional'
        structuralProperties:
          $ref: '#/components/schemas/PrefabElement_structuralProperties'
        performance:
          $ref: '#/components/schemas/PrefabElement_performance'
        sustainability:
          $ref: '#/components/schemas/PrefabElement_sustainability'
        documentationAndCompliance:
          $ref: '#/components/schemas/PrefabElement_documentationAndCompliance'
        installationAndConnectivity:
          $ref: '#/components/schemas/PrefabElement_installationAndConnectivity'
        lifecycleAndMaintenance:
          $ref: '#/components/schemas/PrefabElement_lifecycleAndMaintenance'
        aestheticAndCustomizationOptions:
          $ref: '#/components/schemas/PrefabElement_aestheticAndCustomizationOptions'
        economicFactors:
          $ref: '#/components/schemas/PrefabElement_economicFactors'
      required:
      - boundingBox
      - buildingSystem
      - description
      - dimensional
      - id
      - images
      - material
      - name
      - productCategory
    ElementCreate:
      description: An element to create.
      example:
        boundingBox:
          depth: 1.4658129805029452
          width: 0.8008281904610115
          height: 6.027456183070403
        images:
        - images
        - images
        installationAndConnectivity:
          installationTime: installationTime
          connectionType: Bolt-on
          compatibility: Steel Frame
        buildingSystem: Wall
        dimensional:
          width:
            min: 5.962133916683182
            max: 5.637376656633329
          length:
            min: 5.962133916683182
            max: 5.637376656633329
          height:
            min: 5.962133916683182
            max: 5.637376656633329
        structuralProperties:
          windLoadResistance: Class A
          loadBearingCapacity:
            unit: "N"
            loadDistribution: loadDistribution
            maximumLoad: 2.3021358869347655
          seismicResistance: Zone 1
        lifecycleAndMaintenance:
          maintenanceRequirements: maintenanceRequirements
          warranty: warranty
          expectedLifespan: expectedLifespan
        description: description
        documentationAndCompliance:
          technicalSpecifications: technicalSpecifications
          certifications:
            certificationTypes:
            - certificationTypes
            - certificationTypes
            regulatoryApprovals:
            - regulatoryApprovals
            - regulatoryApprovals
        sustainability:
          countryOfManufacturing: countryOfManufacturing
          recyclability: 0%
          classification: A+
          energyEfficiency: R-1
          VOCEmissions: None
        productCategory: Boarding
        aestheticAndCustomizationOptions:
          colorOptions:
          - colorOptions
          - colorOptions
          texture: texture
          modularAdaptability: modularAdaptability
        performance:
          thermalTransmittance: 1.4122802483006218
          acousticProperties:
            acousticPerformance: acousticPerformance
            soundInsulationRating: soundInsulationRating
          resistanceToFireClassification: A1
        material:
          finishMaterial: Timber
          structuralMaterial: Timber
        name: name
        economicFactors:
          manufacturingLeadTime: manufacturingLeadTime
          costPerUnit: 9.301444243932576
      properties:
        name:
          type: string
        description:
          type: string
        boundingBox:
          $ref: '#/components/schemas/PrefabElement_boundingBox'
        images:
          items:
            type: string
          type: array
        buildingSystem:
          enum:
          - Wall
          - Balcony
          - Pod
          - Frame
          - Facade
          - Floors
          - Modules
          - Plants
          - Roofs
          - Stairs
          type: string
        productCategory:
          enum:
          - Boarding
          - Solid Wall Panels
          - Closed Wall Panels
          - Twinwall
          - Open Wall Panels
          - Structural Insulated Panels (SIPs)
          - Insulated Concrete Panels
          - Prefabricated Balcony
          - Pod
          - Whole Building System
          - Structural Frame
          - Facade System
          - Hollowcore Floor
          - Concrete Lattice Floor
          - Floor Cassettes
          - Solid Floor Panels
          - Volumetric module
          - Prefabricated Plant
          - Roof Panel
          - Roof Truss
          - Prefabricated Stairs
          type: string
        material:
          $ref: '#/components/schemas/PrefabElement_material'
        dimensional:
          $ref: '#/components/schemas/PrefabElement_dimensional'
        structuralProperties:
          $ref: '#/components/schemas/PrefabElement_structuralProperties'
        performance:
          $ref: '#/components/schemas/PrefabElement_performance'
        sustainability:
          $ref: '#/components/schemas/PrefabElement_sustainability'
        documentationAndCompliance:
          $ref: '#/components/schemas/PrefabElement_documentationAndCompliance'
        installationAndConnectivity:
          $ref: '#/components/schemas/PrefabElement_installationAndConnectivity'
        lifecycleAndMaintenance:
          $ref: '#/components/schemas/PrefabElement_lifecycleAndMaintenance'
        aestheticAndCustomizationOptions:
          $ref: '#/components/schemas/PrefabElement_aestheticAndCustomizationOptions'
        economicFactors:
          $ref: '#/components/schemas/PrefabElement_economicFactors'
      required:
      - boundingBox
      - buildingSystem
      - description
      - dimensional
      - images
      - material
      - name
      - productCategory
    PrefabElement_boundingBox:
      description: The bounding box of an element in millimeters.
      example:
        depth: 1.4658129805029452
        width: 0.8008281904610115
        height: 6.027456183070403
      properties:
        width:
          type: number
        height:
          type: number
        depth:
          type: number
      required:
      - depth
      - height
      - width
    PrefabElement_material:
      example:
        finishMaterial: Timber
        structuralMaterial: Timber
      properties:
        finishMaterial:
          enum:
          - Timber
          - Steel
          - Concrete
          - Hybrid
          - Other
          type: string
        structuralMaterial:
          enum:
          - Timber
          - Steel
          - Concrete
          - Hybrid
          - Other
          type: string
      required:
      - finishMaterial
      - structuralMaterial
    PrefabElement_dimensional_width:
      example:
        min: 5.962133916683182
        max: 5.637376656633329
      properties:
        min:
          type: number
        max:
          type: number
      required:
      - max
      - min
    PrefabElement_dimensional:
      example:
        width:
          min: 5.962133916683182
          max: 5.637376656633329
        length:
          min: 5.962133916683182
          max: 5.637376656633329
        height:
          min: 5.962133916683182
          max: 5.637376656633329
      properties:
        width:
          $ref: '#/components/schemas/PrefabElement_dimensional_width'
        height:
          $ref: '#/components/schemas/PrefabElement_dimensional_width'
        length:
          $ref: '#/components/schemas/PrefabElement_dimensional_width'
      required:
      - height
      - length
      - width
    PrefabElement_structuralProperties_loadBearingCapacity:
      example:
        unit: "N"
        loadDistribution: loadDistribution
        maximumLoad: 2.3021358869347655
      properties:
        maximumLoad:
          type: number
        unit:
          enum:
          - "N"
          - kN
          - lbf
          - kgf
          type: string
        loadDistribution:
          type: string
      required:
      - loadDistribution
      - maximumLoad
      - unit
    PrefabElement_structuralProperties:
      example:
        windLoadResistance: Class A
        loadBearingCapacity:
          unit: "N"
          loadDistribution: loadDistribution
          maximumLoad: 2.3021358869347655
        seismicResistance: Zone 1
      properties:
        loadBearingCapacity:
          $ref: '#/components/schemas/PrefabElement_structuralProperties_loadBearingCapacity'
        seismicResistance:
          enum:
          - Zone 1
          - Zone 2
          - Zone 3
          - Zone 4
          type: string
        windLoadResistance:
          enum:
          - Class A
          - Class B
          - Class C
          - Class D
          type: string
    PrefabElement_performance_acousticProperties:
      example:
        acousticPerformance: acousticPerformance
        soundInsulationRating: soundInsulationRating
      properties:
        soundInsulationRating:
          type: string
        acousticPerformance:
          type: string
      required:
      - acousticPerformance
      - soundInsulationRating
    PrefabElement_performance:
      example:
        thermalTransmittance: 1.4122802483006218
        acousticProperties:
          acousticPerformance: acousticPerformance
          soundInsulationRating: soundInsulationRating
        resistanceToFireClassification: A1
      properties:
        resistanceToFireClassification:
          enum:
          - A1
          - A2
          - B
          - C
          - D
          - E
          - F
          - 1-hour
          - 2-hour
          - 3-hour
          - 4-hour
          type: string
        thermalTransmittance:
          maximum: 2
          minimum: 0
          type: number
        acousticProperties:
          $ref: '#/components/schemas/PrefabElement_performance_acousticProperties'
      required:
      - resistanceToFireClassification
      - thermalTransmittance
    PrefabElement_sustainability:
      example:
        countryOfManufacturing: countryOfManufacturing
        recyclability: 0%
        classification: A+
        energyEfficiency: R-1
        VOCEmissions: None
      properties:
        countryOfManufacturing:
          type: string
        classification:
          enum:
          - A+
          - A
          - B
          - C
          - D
          type: string
        VOCEmissions:
          enum:
          - None
          - Low
          - Medium
          - High
          type: string
        recyclability:
          enum:
          - 0%
          - 25%
          - 50%
          - 75%
          - 100%
          type: string
        energyEfficiency:
          enum:
          - R-1
          - R-2
          - R-5
          - Energy Star
          - LEED Certified
          - LEED Silver
          - LEED Gold
          - LEED Platinum
          type: string
      required:
      - classification
      - countryOfManufacturing
    PrefabElement_documentationAndCompliance_certifications:
      example:
        certificationTypes:
        - certificationTypes
        - certificationTypes
        regulatoryApprovals:
        - regulatoryApprovals
        - regulatoryApprovals
      properties:
        certificationTypes:
          items:
            type: string
          type: array
        regulatoryApprovals:
          items:
            type: string
          type: array
      required:
      - certificationTypes
      - regulatoryApprovals
    PrefabElement_documentationAndCompliance:
      example:
        technicalSpecifications: technicalSpecifications
        certifications:
          certificationTypes:
          - certificationTypes
          - certificationTypes
          regulatoryApprovals:
          - regulatoryApprovals
          - regulatoryApprovals
      properties:
        technicalSpecifications:
          type: string
        certifications:
          $ref: '#/components/schemas/PrefabElement_documentationAndCompliance_certifications'
      required:
      - certifications
      - technicalSpecifications
    PrefabElement_installationAndConnectivity:
      example:
        installationTime: installationTime
        connectionType: Bolt-on
        compatibility: Steel Frame
      properties:
        connectionType:
          enum:
          - Bolt-on
          - Welded
          - Clip-on
          - Adhesive
          - Mortar
          type: string
        installationTime:
          type: string
        compatibility:
          enum:
          - Steel Frame
          - Wood Frame
          - Concrete Structure
          - Brickwork
          - Modular Systems
          - Glass Facades
          - Composite Materials
          type: string
    PrefabElement_lifecycleAndMaintenance:
      example:
        maintenanceRequirements: maintenanceRequirements
        warranty: warranty
        expectedLifespan: expectedLifespan
      properties:
        expectedLifespan:
          type: string
        maintenanceRequirements:
          type: string
        warranty:
          type: string
    PrefabElement_aestheticAndCustomizationOptions:
      example:
        colorOptions:
        - colorOptions
        - colorOptions
        texture: texture
        modularAdaptability: modularAdaptability
      properties:
        colorOptions:
          items:
            type: string
          type: array
        texture:
          type: string
        modularAdaptability:
          type: string
    PrefabElement_economicFactors:
      example:
        manufacturingLeadTime: manufacturingLeadTime
        costPerUnit: 9.301444243932576
      properties:
        costPerUnit:
          type: number
        manufacturingLeadTime:
          type: string
  securitySchemes:
    apiKey:
      description: API key for programmatic access.
      in: header
      name: X-API-KEY
      type: apiKey
    bearer:
      bearerFormat: JWT
      description: An embedded jason web token.
      scheme: bearer
      type: http
